services:
  go_service1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8080

  go_service2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8082:8080

  go_service3:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8083:8080

  nginx:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
